name: QA
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

jobs:
  lint:
    uses: canonical/starflow/.github/workflows/lint-python.yaml@main
  test:
    uses: canonical/starflow/.github/workflows/test-python.yaml@main
    with:
      fast-test-platforms: '["ubuntu-22.04", "ubuntu-24.04", "ubuntu-24.04-arm", "windows-latest", "macos-latest"]'
      fast-test-python-versions: '["3.10", "3.11", "3.12", "3.14"]'
      slow-test-platforms: '["ubuntu-22.04", "ubuntu-24.04-arm"]'
      slow-test-python-versions: '["3.10", "3.11", "3.12", "3.14"]'
      extra-env-vars: |
        STAGING_SSO_USERNAME=$SECRET_1
        STAGING_SSO_PASSWORD=$SECRET_2
    secrets:
      secret-1: ${{ vars.STAGING_SSO_USERNAME }}
      secret-2: ${{ secrets.STAGING_SSO_PASSWORD }}
