name: TIOBE TiCS

on:
  push:
    branches:
      - "work/tics"
  schedule:
    - cron: "0 0 * * *" # Daily at midnight

jobs:
  tests:
    uses: canonical/starflow/.github/workflows/analysis.yaml@work/tics
    with:
      platform-tags: '"ubuntu-24.04"'
      project: craft-store
